// <auto-generated />
using System;
using KWHMonitoring.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KWHMonitoring.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KWHMonitoring.Models.AnomalyLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Acknowledged")
                        .HasColumnName("Acknowledged");

                    b.Property<DateTime?>("AcknowledgedTime")
                        .HasColumnName("AcknowledgedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("AnomalyType")
                        .IsRequired()
                        .HasColumnName("AnomalyType")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime>("DetectedTime")
                        .HasColumnName("DetectedTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Deviation")
                        .HasColumnName("Deviation")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("DeviceId")
                        .HasColumnName("DeviceId")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("DeviceKey")
                        .IsRequired()
                        .HasColumnName("DeviceKey")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("EMAValue")
                        .HasColumnName("EMAValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnName("Notes")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<decimal>("PowerValue")
                        .HasColumnName("PowerValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ThresholdMode")
                        .HasColumnName("ThresholdMode")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<decimal>("ThresholdValue")
                        .HasColumnName("ThresholdValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DetectedTime")
                        .HasName("IX_AnomalyLogs_DetectedTime");

                    b.HasIndex("DeviceKey")
                        .HasName("IX_AnomalyLogs_DeviceKey");

                    b.ToTable("AnomalyLogs");
                });

            modelBuilder.Entity("KWHMonitoring.Models.AppLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceKey")
                        .HasColumnName("DeviceKey")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasColumnName("LogLevel")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnName("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Topic")
                        .HasColumnName("Topic")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasName("IX_AppLog_CreatedAt");

                    b.HasIndex("LogLevel")
                        .HasName("IX_AppLog_Level");

                    b.ToTable("AppLog");
                });

            modelBuilder.Entity("KWHMonitoring.Models.AppSettingsRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasColumnName("SettingKey")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnName("SettingValue")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnName("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SettingKey")
                        .IsUnique()
                        .HasName("IX_AppSettings_SettingKey");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("KWHMonitoring.Models.ColumnMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnName("IsActive");

                    b.Property<string>("NewColumnName")
                        .IsRequired()
                        .HasColumnName("NewColumnName")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("OldColumnName")
                        .IsRequired()
                        .HasColumnName("OldColumnName")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("OldColumnName")
                        .IsUnique()
                        .HasName("IX_ColumnMapping_OldName");

                    b.ToTable("ColumnMapping");
                });

            modelBuilder.Entity("KWHMonitoring.Models.ColumnScaleConfig", b =>
                {
                    b.Property<string>("ColumnName")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ColumnName")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Category")
                        .HasColumnName("Category")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnName("DataType")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500);

                    b.Property<bool>("IsDynamic")
                        .HasColumnName("IsDynamic");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnName("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegisterAddress")
                        .HasColumnName("RegisterAddress")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<decimal>("ScaleFactor")
                        .HasColumnName("ScaleFactor")
                        .HasColumnType("decimal(18,5)");

                    b.Property<string>("Unit")
                        .HasColumnName("Unit")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ColumnName");

                    b.ToTable("ColumnScaleConfig");
                });

            modelBuilder.Entity("KWHMonitoring.Models.DailyEnergy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DeviceKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("EnergyKWh")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("DailyEnergy");
                });

            modelBuilder.Entity("KWHMonitoring.Models.DeviceRegistry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnName("DeviceId")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("DeviceKey")
                        .IsRequired()
                        .HasColumnName("DeviceKey")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnName("FirstSeen")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupName")
                        .HasColumnName("GroupName")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool>("IsActive")
                        .HasColumnName("IsActive");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnName("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnName("Location")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<long>("MessageCount")
                        .HasColumnName("MessageCount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnName("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .HasName("IX_DeviceRegistry_DeviceId");

                    b.HasIndex("DeviceKey")
                        .IsUnique()
                        .HasName("IX_DeviceRegistry_DeviceKey");

                    b.ToTable("DeviceRegistry");
                });

            modelBuilder.Entity("KWHMonitoring.Models.FailedMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsResolved")
                        .HasColumnName("IsResolved");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnName("Payload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnName("Reason")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnName("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnName("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnName("RetryCount");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnName("Topic")
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.HasIndex("IsResolved")
                        .HasName("IX_FailedMessages_IsResolved");

                    b.HasIndex("ReceivedAt")
                        .HasName("IX_FailedMessages_ReceivedAt");

                    b.ToTable("FailedMessages");
                });

            modelBuilder.Entity("KWHMonitoring.Models.HourlyEnergy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("EnergyKWh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Hour")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HourlyEnergy");
                });

            modelBuilder.Entity("KWHMonitoring.Models.KWHData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Amp_R")
                        .HasColumnName("AMPERE_R")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("Amp_S")
                        .HasColumnName("AMPERE_S")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("Amp_T")
                        .HasColumnName("AMPERE_T")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("Cos_Phi")
                        .HasColumnName("CosPhi")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("Daya_Watt")
                        .HasColumnName("W")
                        .HasColumnType("decimal(18,1)");

                    b.Property<string>("DeviceId")
                        .HasColumnName("DeviceId")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("DeviceKey")
                        .IsRequired()
                        .HasColumnName("DeviceKey")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<decimal?>("Energi_Aktif_Wh")
                        .HasColumnName("Aktif_Power")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Frekuensi_Hz")
                        .HasColumnName("F")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GroupName")
                        .HasColumnName("GroupName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal?>("TotalW1M_Wh")
                        .HasColumnName("TotalW1M")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Total_Energy_Wh")
                        .HasColumnName("TotalW")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Volt_R")
                        .HasColumnName("PHASE_R")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Volt_S")
                        .HasColumnName("PHASE_S")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Volt_T")
                        .HasColumnName("PHASE_T")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Waktu_Device")
                        .HasColumnName("TerminalTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Waktu_Server")
                        .HasColumnName("ReceivedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceKey")
                        .HasName("IX_KWHData_DeviceKey");

                    b.HasIndex("Waktu_Device")
                        .HasName("IX_KWHData_TerminalTime");

                    b.HasIndex("Waktu_Server")
                        .HasName("IX_KWHData_ReceivedTime");

                    b.HasIndex("DeviceKey", "Waktu_Server")
                        .HasName("IX_KWHData_DeviceKey_TerminalTime");

                    b.ToTable("KWHData");
                });

            modelBuilder.Entity("KWHMonitoring.Models.KWHDataHistory", b =>
                {
                    b.Property<long>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("HistoryId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("AktifPower")
                        .HasColumnName("Aktif_Power")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AmpereR")
                        .HasColumnName("AMPERE_R")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("AmpereS")
                        .HasColumnName("AMPERE_S")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("AmpereT")
                        .HasColumnName("AMPERE_T")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime>("ArchivedAt")
                        .HasColumnName("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CosPhi")
                        .HasColumnName("CosPhi")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("DeviceId")
                        .HasColumnName("DeviceId")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("DeviceKey")
                        .IsRequired()
                        .HasColumnName("DeviceKey")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<decimal?>("F")
                        .HasColumnName("F")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GroupName")
                        .HasColumnName("GroupName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<long>("OriginalId")
                        .HasColumnName("OriginalId");

                    b.Property<decimal?>("PhaseR")
                        .HasColumnName("PHASE_R")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PhaseS")
                        .HasColumnName("PHASE_S")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PhaseT")
                        .HasColumnName("PHASE_T")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReceivedTime")
                        .HasColumnName("ReceivedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TerminalTime")
                        .HasColumnName("TerminalTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TotalW")
                        .HasColumnName("TotalW")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalW1M")
                        .HasColumnName("TotalW1M")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("W")
                        .HasColumnName("W")
                        .HasColumnType("decimal(18,1)");

                    b.HasKey("HistoryId");

                    b.HasIndex("ArchivedAt")
                        .HasName("IX_KWHData_History_ArchivedAt");

                    b.HasIndex("DeviceKey")
                        .HasName("IX_KWHData_History_DeviceKey");

                    b.ToTable("KWHData_History");
                });

            modelBuilder.Entity("KWHMonitoring.Models.MonthlyEnergy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("EnergyKWh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Month");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("MonthlyEnergy");
                });

            modelBuilder.Entity("KWHMonitoring.Models.YearlyEnergy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("EnergyKWh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("YearlyEnergy");
                });

            modelBuilder.Entity("KWHMonitoring.Models.KWHData", b =>
                {
                    b.HasOne("KWHMonitoring.Models.DeviceRegistry")
                        .WithMany()
                        .HasForeignKey("DeviceKey")
                        .HasConstraintName("FK_KWHData_DeviceRegistry")
                        .HasPrincipalKey("DeviceKey")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
